# **SpendDNA, Anusha Sridhar, DATA ANALYTICS July 2026 batch, 29/08/26**

## ***TRANSACTION PARSER***

In [ ]:
import pandas as pd, numpy as np
from datetime import datetime, date as dt

In [ ]:
# To read the file
df = pd.read_csv('rahul_transactions.csv')

In [ ]:
# To see how the dataset looks like
df

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962
...,...,...,...,...,...,...,...,...
1323,2024-06-30,11:53,SWIGGY-INSTAMART,DR,637.00,-311783.0,UPI,TXN274261
1324,30 Jun 2024,16:35,BHIM ZEPTO,DR,693.00,-312476.0,UPI,TXN792601
1325,30/06/24,17:12,UPI-STARBUCKS@AXIS,DR,327.00,-310557.0,UPI,TXN859233
1326,2024-06-30,19:56,POS ZOMATO,DR,₹589,-311146.0,UPI,TXN492729
1327,30/06/24,22:27,OLA ELECTRIC,DR,₹208,-312684.0,UPI,TXN910085

In [ ]:
# Column heads of the dataset
df.columns

Index(['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode',
       'Ref'],
      dtype='object')

In [ ]:
# To see the type of data stored in each column and to understand whether the data type is applicable to that column
#Here we can see that amount is stored as an object. This is not possible as it's numerical data. Hence it has to be stored as an integer or float

df.dtypes

Date            object
Time            object
Description     object
Type            object
Amount          object
Balance        float64
Mode            object
Ref             object
dtype: object

In [ ]:
# To check the number of duplicated values in the dataset. THere are 18 in total
df.duplicated().sum()

np.int64(18)

In [ ]:
# To drop the duplicates from the original dataset
df.drop_duplicates(inplace=True)

In [ ]:
# Again checking whether any duplicates are present in the dataset after dropping them
df.duplicated().sum()

np.int64(0)

In [ ]:
# After dropping 18 duplicates from 1328 observation the dimension of the data reduces to 1310 observations under each column.
df.shape

(1310, 8)

In [ ]:
# Parsing all the four types of dates in the Date column and storing it in a different data frame named 'date'
df['date'] = pd.to_datetime(df['Date'], errors='coerce', dayfirst=True, format='mixed')

In [ ]:
# To record time from 'date' column in which a transaction took place
df['hour'] = df['Time'].str[:2].astype(int)

# To record months from 'date' column in which a transaction took place
df['month'] = df['date'].dt.month

# To record specific days of the from 'date' column when a transaction took place
df['day_of_week'] = df['date'].dt.day_name()

# To record specific weeks of the calendar from 'date' column
df['week_number'] = df['date'].dt.isocalendar().week

In [ ]:
# To check whether all the dates have been parsed
df['date'].count()

np.int64(1310)

In [ ]:
# To remove timestamp from 'date'
df['date'] = df['date'].dt.strftime('%Y-%m-%d')

In [ ]:
# To remove special characters like ',', '₹' and 'Rs.' from 'Amount' column. This is essential so as to convert Amount into numerical data.
df['Amount'] = df['Amount'].str.replace('₹', '').str.replace('Rs.', '').str.replace(',', '').str.strip()

In [ ]:
# Converting Amount into numerical data
df['Amount'] = pd.to_numeric(df['Amount'], errors='coerce')

In [ ]:
# Checking whether amount is stored as a numerical value that is a float or int type
df['Amount']

0        2462.0
1          50.0
2       84728.0
3        1828.0
4         270.0
         ...
1323      637.0
1324      693.0
1325      327.0
1326      589.0
1327      208.0
Name: Amount, Length: 1310, dtype: float64

In [ ]:
# Replacing records 'CR' and 'DR' with 'credit' and 'debit' respectively under 'Type' column
df['Type'] = df['Type'].str.replace('DR','debit').str.replace('CR','credit').str.strip()

In [ ]:
# Standardising format so that records like 'Credit' and 'Debit' are stored as 'credit' and 'debit' respectively under 'Type' column
df['Type'] = df['Type'].str.lower()

In [ ]:
# Checking whether the previous codes fro 'Type' column ran successfully
df['Type']

0        debit
1        debit
2       credit
3        debit
4        debit
         ...
1323     debit
1324     debit
1325     debit
1326     debit
1327     debit
Name: Type, Length: 1310, dtype: object

In [ ]:
# Basic information of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1310 entries, 0 to 1327
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         1310 non-null   object
 1   Time         1310 non-null   object
 2   Description  1310 non-null   object
 3   Type         1310 non-null   object
 4   Amount       1310 non-null   float64
 5   Balance      1310 non-null   float64
 6   Mode         1310 non-null   object
 7   Ref          1310 non-null   object
 8   date         1310 non-null   object
 9   hour         1310 non-null   int64
 10  month        1310 non-null   int32
 11  day_of_week  1310 non-null   object
 12  week_number  1310 non-null   UInt32
dtypes: UInt32(1), float64(2), int32(1), int64(1), object(8)
memory usage: 134.3+ KB

In [ ]:
Transaction_Parser = print(f"Parsed {len(df)} transactions across 6 months. Dropped 18 duplicates. 0 unparseable amounts, 0 unparseable dates. ")

Parsed 1310 transactions across 6 months. Dropped 18 duplicates. 0 unparseable amounts, 0 unparseable dates.

## ***VENDOR EXTRACTOR***

In [ ]:
df['Description'].unique()

array(['AMAZON SELLER SVCS', 'BHIM-BMTC',
       'NEFT-TECHCRUSH LABS-SALARY MAY24', 'UPI-AMAN-8934@OKAXIS',
       'BHIM-BLINKIT', 'BHIM ZEPTO', 'UPI-UBER-2426@HDFCBANK',
       'POS SWIGGY BANGALORE', 'UPI-GROWWPAY@HDFCBANK', 'OLA ELECTRIC',
       'BMS MOVIE TICKETS', 'POS OLA-PRIME', 'SWIGGY-INSTAMART',
       'UPI-STARBUCKS@AXIS', 'UPI-THIRDWAVE@OKAXIS', 'ANI Technologies',
       'BMTC BUS PASS', 'POS TRUFFLES', 'FLIPKART INDIA',
       'POS SWIGGY-RESTAURANT', 'GROFERS INDIA P L', 'POS UBER BANGALORE',
       'BANGALORE ELEC SUPPLY', 'TWC INDIA', 'UPI-BESCOM-BILL@HDFCBANK',
       'UPI-AMAN-0816@OKAXIS', 'ROPPEN TRANSPORTATION', 'OLA CABS',
       'POS ZOMATO', 'UPI-AMAZONPAY@HDFCBANK', 'POS BLINKIT',
       'IMPS-RENT-LANDLORD-75500265', 'ZOMATO MEDIA P L',
       'UPI-ANKIT-6430@OKAXIS', 'UPI-OLACABS@HDFCBANK',
       'UPI-JIORECHARGE@PAYTM', 'UPI-CCD@HDFCBANK', 'Swiggy*Order',
       'INSTAMART BANGALORE', 'UPI-ZOMATO-LIMITED@PAYTM',
       'AVENUE SUPERMARTS', 'POS HP PETROL STATION',
       'UPI-VIKAS-6060@OKAXIS', 'POS BANGALORE RESTAURANT',
       'UPI-ZERODHA-COIN@AXIS', 'BHIM SWIGGY', 'UPI-BOOKMYSHOW@HDFCBANK',
       'BLINKIT BANGALORE', 'POS ZEPTO BANGALORE', 'UPI-DMART@OKAXIS',
       'UPI-RAPIDO@OKAXIS', 'BUNDL Tech P L', 'TATA STARBUCKS',
       'POS CAFE COFFEE DAY', 'UBER SYSTEMS INDIA', 'UPI-MYNTRA@HDFCBANK',
       'UPI-FLIPKART@HDFCBANK', 'UPI-BWSSB@AXIS',
       'UPI-ZOMATO6393@OKICICI', 'AMAZON IN', 'UPI-NETFLIX-MEMB@HDFCBANK',
       'AIRTEL POSTPAID', 'Amazon Pay India', 'UPI-PRIYA-2221@OKAXIS',
       'POS FLIPKART BANGALORE', 'POS NYKAA BANGALORE', 'VI POSTPAID',
       'UPI-UBER-6457@HDFCBANK', 'POS BPCL PETROL PUMP', 'TUMMOC-BMTC',
       'POS INDIAN OIL BANGALORE', 'UPI-SPOTIFY-IN@AXIS', 'POS DINEOUT',
       'UPI-BLINKIT-0656@PAYTM', 'UPI-SWIGGY5057@OKAXIS', 'ZOMATO-DINING',
       'COFFEE DAY GLOBAL', 'UPI-NYKAA@AXIS', 'UPI-SWIGGY9672@OKAXIS',
       'RAPIDO BIKE TAXI', 'UPI-SWIGGY-6560@HDFCBANK', 'DISNEY HOTSTAR',
       'NEFT ZERODHA BROKING', 'UBER INDIA', 'AMAZONIN MARKETPLACE',
       'UPI-ZOMATO4674@OKICICI', 'POS EMPIRE RESTAURANT',
       'ATM-WDL-SBI-5715', 'UPI-SWIGGY-9474@HDFCBANK',
       'POS MEGHANA FOODS', 'ZEPTO MARKETPLACE', 'UPI-IOC9075@HDFCBANK',
       'UPI-SWIGGY-2954@HDFCBANK', 'FKART INTRNET',
       'UPI-SWIGGY-5808@HDFCBANK', 'UPI-BIGBASKET@HDFCBANK',
       'AMZN-INTPYMT', 'AMZN PRIME', 'MYNTRA-ORDER',
       'UPI-SWIGGY-5551@HDFCBANK', 'BUNDL TECH-INSTAMART',
       'MYNTRA DESIGNS', 'POS MYNTRA', 'POS DMART BANGALORE',
       'BIGBASKET BANGALORE', 'POS THIRD WAVE COFFEE', 'SPOTIFY INDIA',
       'UPI-SWIGGY-7959@HDFCBANK', 'UPI-BLINKIT-3798@PAYTM',
       'UPI-BLINKIT-3397@PAYTM', 'UPI-SWIGGY-INSTAMART@OKAXIS',
       'ZOMATO BENGALURU', 'BESCOM ELEC BILL',
       'IMPS-RENT-LANDLORD-39598076', 'UPI-RESTAURANT-7285@PAYTM',
       'POS STARBUCKS BANGALORE', 'UPI-SWIGGY2461@OKAXIS',
       'UPI-SWIGGY4619@OKAXIS', 'IMPS ZERODHA-COIN',
       'UPI-SWIGGY3675@OKAXIS', 'RELIANCE JIO',
       'UPI-SWIGGY-1309@HDFCBANK', 'NETFLIX ENTERTAINMENT',
       'UPI-UBER-5667@HDFCBANK', 'FSN E-COMMERCE',
       'UPI-BLINKIT-2630@PAYTM', 'UPI-RESTAURANT-7678@PAYTM',
       'ATM-WDL-HDFC-4942', 'Uber*Trip', 'UPI-SWIGGY1616@OKAXIS',
       'UPI-NEHA-9795@OKAXIS', 'BIGTREE ENTERTAINMENT',
       'UPI-ZOMATO4177@OKICICI', 'INNOVATIVE RETAIL', 'POS INSTAMART',
       'UPI-RESTAURANT-3715@PAYTM', 'UPI-UBER-1232@HDFCBANK',
       'STAR INDIA PVT LTD', 'UPI-SWIGGY-5933@HDFCBANK',
       'UPI-RESTAURANT-0251@PAYTM', 'UPI-ZOMATO3977@OKICICI',
       'UPI-BLINKIT-7138@PAYTM', 'UPI-SWIGGY8086@OKAXIS',
       'UPI-SWIGGY-6605@HDFCBANK', 'AMAZON PRIME VIDEO',
       'UPI-SWIGGY-7844@HDFCBANK', 'UPI-SWIGGY-1487@HDFCBANK',
       'UPI-UBER-6248@HDFCBANK', 'UPI-NEHA-5906@OKAXIS',
       'KIRANAKART TECH', 'UPI-SWIGGY-7642@HDFCBANK',
       'UPI-ZEPTO-4547@HDFCBANK', 'UPI-ZEPTO-4563@HDFCBANK',
       'IMPS-RENT-LANDLORD-51148088', 'UPI-RESTAURANT-6377@PAYTM',
       'UPI-ZEPTO-3309@HDFCBANK', 'UPI-ZEPTO-0070@HDFCBANK',
       'UPI-SWIGGY-8169@HDFCBANK', 'UPI-VIKAS-5416@OKAXIS',
       'UPI-HOTSTAR@AXIS', 'ATM-WDL-HDFC-9140', 'UPI-ZOMATO6436@OKICICI',
       'ATM-WDL-SBI-4080', 'NETFLIX.COM', 'UPI-IOC0494@HDFCBANK',
       'UPI-RESTAURANT-4630@PAYTM', 'UPI-IOC1246@HDFCBANK',
       'Flipkart Internet', 'UPI-SWIGGY1600@OKAXIS',
       'UPI-SWIGGY8576@OKAXIS', 'ATM-WDL-HDFC-8030', 'SPOTIFY*PREMIUM',
       'UPI-BLINKIT-6907@PAYTM', 'BWSSB WATER BILL',
       'UPI-RESTAURANT-7888@PAYTM', 'GROWW INVEST TECH',
       'UPI-IOC2000@HDFCBANK', 'UPI-SWIGGY5466@OKAXIS',
       'UPI-SNEHA-0942@OKAXIS', 'UPI-SWIGGY-2664@HDFCBANK', 'JIOFIBER',
       'BHARTI AIRTEL LTD', 'UPI-UBER-0377@HDFCBANK',
       'UPI-UBER-5112@HDFCBANK', 'UPI-ZOMATO1274@OKICICI',
       'UPI-SWIGGY4144@OKAXIS', 'UPI-VI-RECHARGE@HDFCBANK',
       'UPI-KARAN-5789@OKAXIS', 'UPI-BLINKIT-1501@PAYTM',
       'ZERODHA-MF SIP', 'UPI-SWIGGY-9575@HDFCBANK',
       'UPI-RESTAURANT-0753@PAYTM', 'NEXTBILLION-GROWW',
       'UPI-ZOMATO5010@OKICICI', 'UPI-BLINKIT-1469@PAYTM',
       'UPI-SWIGGY9328@OKAXIS', 'NYKAA E-RETAIL', 'ATM-WDL-HDFC-3609',
       'UPI-SWIGGY0226@OKAXIS', 'UPI-SWIGGY9600@OKAXIS',
       'IMPS-RENT-LANDLORD-36852906', 'UPI-ZOMATO7344@OKICICI',
       'UPI-ZEPTO-9191@HDFCBANK', 'UPI-ZOMATO9481@OKICICI',
       'UPI-IOC2115@HDFCBANK', 'UPI-SWIGGY-3513@HDFCBANK',
       'UPI-RESTAURANT-3549@PAYTM', 'UPI-PRIYA-8750@OKAXIS',
       'UPI-ZOMATO5845@OKICICI', 'UPI-ZEPTO-6004@HDFCBANK',
       'UPI-BLINKIT-3223@PAYTM', 'UPI-SWIGGY1998@OKAXIS',
       'ATM-WDL-ICICI-6478', 'UPI-SWIGGY0250@OKAXIS',
       'UPI-RESTAURANT-5630@PAYTM', 'UPI-SWIGGY0894@OKAXIS',
       'UPI-ANKIT-9877@OKAXIS', 'UPI-SWIGGY6412@OKAXIS',
       'UPI-SWIGGY-1791@HDFCBANK', 'UPI-SWIGGY5867@OKAXIS',
       'UPI-UBER-8525@HDFCBANK', 'UPI-SWIGGY-4758@HDFCBANK',
       'UPI-BLINKIT-1165@PAYTM', 'UPI-SWIGGY4389@OKAXIS',
       'ATM-WDL-SBI-0237', 'IMPS-RENT-LANDLORD-49966195',
       'UPI-SWIGGY8720@OKAXIS', 'UPI-PRIYA-0104@OKAXIS',
       'UPI-RESTAURANT-8932@PAYTM', 'UPI-SWIGGY9756@OKAXIS',
       'UPI-SWIGGY-1714@HDFCBANK', 'VODAFONE IDEA LTD',
       'ATM-WDL-SBI-0279', 'UPI-SWIGGY-6024@HDFCBANK',
       'UPI-ZEPTO-2913@HDFCBANK', 'UPI-ZOMATO5406@OKICICI',
       'UPI-RESTAURANT-3964@PAYTM', 'UPI-SWIGGY5737@OKAXIS',
       'ATM-WDL-HDFC-8253', 'ZERODHA SECURITIES',
       'UPI-AMAZON-PRIME@HDFCBANK', 'UPI-UBER-4781@HDFCBANK',
       'UPI-RESTAURANT-5691@PAYTM', 'UPI-SWIGGY2847@OKAXIS',
       'UPI-ZOMATO9682@OKICICI', 'UPI-IOC5182@HDFCBANK',
       'UPI-ANKIT-5946@OKAXIS', 'UPI-SWIGGY9088@OKAXIS',
       'UPI-UBER-1392@HDFCBANK', 'UPI-SWIGGY9983@OKAXIS',
       'UPI-ZEPTO-1050@HDFCBANK', 'UPI-ANKIT-1837@OKAXIS',
       'IMPS-RENT-LANDLORD-35126704', 'UPI-SWIGGY8392@OKAXIS',
       'UPI-ZOMATO5117@OKICICI', 'UPI-ZOMATO4622@OKICICI',
       'UPI-SWIGGY1418@OKAXIS', 'ATM-WDL-ICICI-9135',
       'UPI-RESTAURANT-5531@PAYTM', 'UPI-ANKIT-6092@OKAXIS',
       'UPI-SWIGGY7538@OKAXIS', 'ATM-WDL-ICICI-4172',
       'UPI-ZEPTO-5207@HDFCBANK', 'ATM-WDL-SBI-4084',
       'UPI-ZEPTO-7106@HDFCBANK', 'ATM-WDL-ICICI-4739',
       'UPI-SWIGGY6053@OKAXIS', 'UPI-SWIGGY-3505@HDFCBANK',
       'UPI-SWIGGY-0015@HDFCBANK', 'UPI-RESTAURANT-2648@PAYTM',
       'ATM-WDL-SBI-0874', 'UPI-VIKAS-1878@OKAXIS',
       'UPI-SWIGGY6013@OKAXIS', 'UPI-SWIGGY-8838@HDFCBANK',
       'UPI-VIKAS-9964@OKAXIS', 'UPI-RESTAURANT-7645@PAYTM',
       'ATM-WDL-ICICI-3918', 'UPI-SWIGGY-9077@HDFCBANK',
       'UPI-RESTAURANT-0874@PAYTM', 'ATM-WDL-ICICI-5025',
       'UPI-SWIGGY3466@OKAXIS', 'UPI-BLINKIT-1828@PAYTM',
       'UPI-UBER-3218@HDFCBANK'], dtype=object)

In [ ]:
# Defining a function for extraxting vendors
def extract_vendor(description):
    descript_upper = description.upper()

    # Defining a dictionary for vendors with the canonical vendor names
    vendor = {
        'Swiggy': ['SWIGGY', 'BUNDL'],
        'Zomato': ['ZOMATO'],
        'Zepto': ['ZEPTO', 'KIRANAKART'],
        'Blinkit': ['BLINKIT', 'GROFERS'],
        'DMart': ['DMART','AVENUE SUPERMARTS'],
        'Instamart': ['INSTAMART'],
        'Amazon': ['AMAZON', 'AMZN'],
        'Flipkart': ['FLIPKART', 'FKART'],
        'Nykaa': ['NYKAA', 'FSN'],
        'Myntra': ['MYNTRA'],
        'Uber': ['UBER'],
        'Ola': ['OLA', 'ANI'],
        'BMTC': ['BMTC'],
        'Rapido': ['RAPIDO', 'ROPPEN TRANSPORTATION'],
        'SALARY': ['SALARY'],
        'Water Bill': ['BWSSB'],
        'Starbucks': ['STARBUCKS'],
        'CCD': ['CCD','CAFE COFFEE DAY'],
        'Coffee Day Global': ['COFFEE DAY GLOBAL'],
        'Third Wave': ['THIRD WAVE', 'THIRDWAVE'],
        'McDonalds': ['MCDONALD'],
        'Dominos': ['DOMINO'],
        'MEGHANA FOODS': ['MEGHANA FOODS'],
        'RESTAURANT': ['RESTAURANT'],
        'TRUFFLES': ['TRUFFLES'],
        'EMPIRE RESTAURANT': ['EMPIRE RESTAURANT'],
        'RESTAURANT': ['RESTAURANT'],
        'TRUFFLES RESTAURANT': ['TRUFFLES'],
        'EMPIRE RESTAURANT': ['EMPIRE RESTAURANT'],
        'Bangalore Restaurant': ['BANGALORE RESTAURANT'],
        'Netflix': ['NETFLIX'],
        'Amazon Prime': ['PRIME'],
        'HOTSTAR': ['HOTSTAR', 'STAR INDIA'],
        'Spotify': ['SPOTIFY'],
        'YouTube': ['YOUTUBE'],
        'Airtel': ['AIRTEL'],
        'Reliance Jio': ['RELIANCE JIO', 'JIO'],
        'Vodafone Idea Pvt Ltd': ['VODAFONE IDEA', 'VI', 'RECHARGE'],
        'BESCOM': ['BESCOM', 'BANGALORE ELEC SUPPLY'],
        'BigBasket': ['BIGBASKET', 'INNOVATIVE RETAIL'],
        'Zerodha': ['ZERODHA'],
        'Groww': ['GROWW'],
        'DINEOUT': ['DINEOUT'],
        'HPCL': ['HPCL', 'HP PETROL'],
        'BPCL': ['BPCL'],
        'IOCL': ['IOCL', 'INDIAN OIL', 'IOC'],
        'TWC India Pvt Ltd': ['TWC'],
        'BookMyShow': ['BOOKMYSHOW', 'BMS', 'BIGTREE ENTERTAINMENT'],
        'P2P Transfer': ['UPI-PRIYA', 'UPI-ANKIT', 'UPI-AMAN', 'UPI-RAHUL', 'UPI-VIKAS', 'UPI-SNEHA', 'UPI-NEHA', 'UPI-KARAN', 'PAYTM-P2P'],
        'Cash Withdrawal': ['ATM-WDL', 'ATM']
    }

    # Differentiating between random ('Uncategorised) and unique vendors
    for canonical, keywords in vendor.items():
        if any(keyword in descript_upper for keyword in keywords):
            return canonical

    return 'Uncategorised'

In [ ]:
# Creating a vendor_clean column to the DataFrame
df['vendor_clean'] = df['Description'].apply(extract_vendor)

In [ ]:
# Computing the number of unique vendors
df['vendor_clean'].nunique()

42

In [ ]:
# Checking top 10 vendors
df['vendor_clean'].value_counts().head(10)

vendor_clean
Swiggy       223
Zomato       121
Ola           87
Amazon        86
Uber          71
Zepto         71
Rapido        55
Blinkit       55
Flipkart      47
Starbucks     42
Name: count, dtype: int64

## ***CATEGORY TAGGER***

In [ ]:
# Creating a dictionary for different categories each vendor belongs to
categories = {'Swiggy': 'Food Delivery',
        'Zomato': 'Food Delivery',
        'Zepto': 'Quick Commerce',
        'Blinkit': 'Quick Commerce',
        'Instamart': 'Quick Commerce',
        'Amazon': 'E-commerce',
        'Flipkart': 'E-commerce',
        'Myntra': 'E-commerce',
        'Nykaa': 'E-commerce',
        'Uber': 'Transport',
        'Ola': 'Transport',
        'Rapido': 'Transport',
        'BMTC': 'Transport',
        'RENT': 'Utilities',
        'Water Bill': 'Utilities',
        'BESCOM': 'Utilities',
        'Vodafone Idea Pvt Ltd': 'Utilities',
        'Starbucks': 'Cafe',
        'CCD': 'Cafe',
        'Third Wave': 'Cafe',
        'Coffee Day Global': 'Cafe',
        'Bangalore Restaurant': 'Restaurants',
        'TRUFFLES RESTAURANT': 'Restaurants',
        'EMPIRE RESTAURANT': 'Restaurants',
        'RESTAURANT': 'Restaurants',
        'MEGHANA FOODS': 'Restaurants',
        'McDonalds': 'Restaurants',
        'Dominos': 'Restaurants',
        'Netflix': 'Subscriptions',
        'Amazon Prime': 'Subscriptions',
        'HOTSTAR': 'Subscription',
        'Spotify': 'Subscription',
        'YouTube': 'Entertainment',
        'Airtel': 'Utilities',
        'Reliance Jio': 'Utilities',
        'BigBasket': 'Quick Commerce',
        'DMart': 'Groceries',
       'Zerodha': 'Investments',
        'Groww': 'Investments',
        'HPCL': 'Fuel',
        'BPCL': 'Fuel',
        'IOCL': 'Fuel',
        'BookMyShow': 'Entertainment',
        'P2P Transfer': 'Personal Transfer',
        'Cash Withdrawal': 'Cash Withdrawal'
    }

In [ ]:
# Creating a new column 'category' which maps each vendor to the category they belong to
df['category'] = df['vendor_clean'].map(categories)

In [ ]:
df['category']

0              E-commerce
1               Transport
2                     NaN
3       Personal Transfer
4          Quick Commerce
              ...
1323        Food Delivery
1324       Quick Commerce
1325                 Cafe
1326        Food Delivery
1327            Transport
Name: category, Length: 1310, dtype: object

In [ ]:
# Computing number of vendors under each categories
df['category'].value_counts()

category
Food Delivery        344
Transport            250
E-commerce           172
Quick Commerce       165
Cafe                  90
Restaurants           54
Utilities             54
Fuel                  28
Investments           23
Groceries             22
Subscription          21
Cash Withdrawal       17
Personal Transfer     14
Subscriptions         10
Entertainment          6
Name: count, dtype: int64

## ***SPENDING OVERVIEW***

In [ ]:
# Getting total debits, total credits, total savings and savings rate

total_credits = df[df['Type'] == 'credit']['Amount'].sum()
total_debits = df[df['Type'] == 'debit']['Amount'].sum()
total_savings = total_credits - total_debits
savings_rate = (total_savings / total_credits) * 100

In [ ]:
print(total_credits)
print(total_debits)
print(total_savings)
print(savings_rate)

# From the above print statement it's observed that my Credits have matched with the expected outcome in the PDF containing the brief of the project. But the Debits did not.
# I ran my codes several time but I'm getting the same answer. Hence savings and savings rate don't match with the expected outcome.
# I checked this in Gemini and it says my codes are right and that in the pdf they are counting debits labeled as 'DR'. But Feature 1 specifically says that all debits to be recorded as 'DR'

509774.0
1678901.0
-1169127.0
-229.34221831635196

In [ ]:
# Computing Amount spent on each vendor and each category the vendors belong to
category_spends = df[df['Type'] == 'debit'].groupby('category')['Amount'].sum().sort_values(ascending=False)
vendor_spends = df[df['Type'] == 'debit'].groupby('vendor_clean')['Amount'].sum().sort_values(ascending=False)

In [ ]:
# Expenditure on top 5 vendors and each category the vendors belong to
print(category_spends[0:5])
print(vendor_spends[0:5])

category
E-commerce        603877.0
Investments       248160.0
Food Delivery     150839.0
Quick Commerce     95826.0
Fuel               89303.0
Name: Amount, dtype: float64
vendor_clean
Amazon           328530.0
Zerodha          210000.0
Flipkart         177510.0
Uncategorised    108000.0
Swiggy            95523.0
Name: Amount, dtype: float64

In [ ]:
# Percentage of expenditure on each category out of total debits
food_percent_deb = (category_spends['Food Delivery'] / total_debits) * 100
qcom_percent_deb = (category_spends['Quick Commerce'] / total_debits) * 100
ecom_percent_deb = (category_spends['E-commerce'] / total_debits) * 100
trans_percent_deb = (category_spends['Transport'] / total_debits) * 100
util_percent_deb = (category_spends['Utilities'] / total_debits) * 100
inv_percent_deb = (category_spends['Investments'] / total_debits) * 100
cafe_percent_deb = (category_spends['Cafe'] / total_debits) * 100
rest_percent_deb = (category_spends['Restaurants'] / total_debits) * 100

In [ ]:
print(food_percent_deb)
print(qcom_percent_deb)
print(ecom_percent_deb)
print(trans_percent_deb)
print(util_percent_deb)
print(inv_percent_deb)
print(cafe_percent_deb)
print(rest_percent_deb)

8.984389192692124
5.70766233387198
35.968588975764504
3.4233108444154836
3.0231085692366615
14.781097872953797
1.6769898880279421
4.838820156757307

# ***MONTHLY TREND ANALYSIS***

In [ ]:
# Building a matrix to record expenditure in each month on each category of vendor
month_pivot = df.pivot_table(values='Amount', index='category', columns='month', aggfunc='sum')
Months = {1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr', 5: 'May', 6: 'Jun'}
month_pivot = month_pivot.rename(columns=Months)

In [ ]:
month_pivot

month                  Jan      Feb       Mar      Apr      May       Jun
category
Cafe                3418.0   3452.0    5068.0   5864.0   5259.0    5094.0
Cash Withdrawal     2000.0   5000.0    8000.0   5500.0   8000.0   17000.0
E-commerce         98623.0  94011.0  108215.0  69219.0  95776.0  138033.0
Entertainment        952.0    474.0     562.0   2224.0      NaN       NaN
Food Delivery      22633.0  23740.0   24803.0  27756.0  25408.0   26499.0
Fuel               30322.0   2079.0   26164.0  18718.0   9138.0    2882.0
Groceries          14594.0   3873.0    3658.0   3334.0   7227.0    4777.0
Investments        38432.0  15000.0   68644.0  54126.0  48628.0   23330.0
Personal Transfer   7523.0   4285.0    2415.0    663.0   3412.0    1541.0
Quick Commerce     14109.0  19875.0   16657.0  20284.0  14438.0   10463.0
Restaurants        12635.0  16679.0   15328.0   5263.0  17934.0   13400.0
Subscription        2433.0   3830.0    2149.0   1749.0   1425.0    2333.0
Subscriptions        334.0    798.0    1360.0    419.0    419.0    1222.0
Transport          11005.0  10191.0    6857.0   9284.0  13141.0    6996.0
Utilities           9797.0   6870.0    9213.0   5831.0   4340.0   14704.0

In [ ]:
last_month = df[df['month'] == 6].groupby('category')['Amount'].sum()

In [ ]:
last_month

category
Cafe                   5094.0
Cash Withdrawal       17000.0
E-commerce           138033.0
Food Delivery         26499.0
Fuel                   2882.0
Groceries              4777.0
Investments           23330.0
Personal Transfer      1541.0
Quick Commerce        10463.0
Restaurants           13400.0
Subscription           2333.0
Subscriptions          1222.0
Transport              6996.0
Utilities             14704.0
Name: Amount, dtype: float64

In [ ]:
first_month = df[df['month'] == 1].groupby('category')['Amount'].sum()

In [ ]:
first_month

category
Cafe                  3418.0
Cash Withdrawal       2000.0
E-commerce           98623.0
Entertainment          952.0
Food Delivery        22633.0
Fuel                 30322.0
Groceries            14594.0
Investments          38432.0
Personal Transfer     7523.0
Quick Commerce       14109.0
Restaurants          12635.0
Subscription          2433.0
Subscriptions          334.0
Transport            11005.0
Utilities             9797.0
Name: Amount, dtype: float64

In [ ]:
biggest_growth = ((last_month - first_month) / first_month) * 100

In [ ]:
biggest_growth

category
Cafe                  49.034523
Cash Withdrawal      750.000000
E-commerce            39.960253
Entertainment               NaN
Food Delivery         17.081253
Fuel                 -90.495350
Groceries            -67.267370
Investments          -39.295379
Personal Transfer    -79.516150
Quick Commerce       -25.841661
Restaurants            6.054610
Subscription          -4.110152
Subscriptions        265.868263
Transport            -36.428896
Utilities             50.086761
Name: Amount, dtype: float64

In [ ]:
# BIGGEST month on-month growth belongs to category 'Food Delivery'
biggest_growth.max()

750.0

In [ ]:
#  BIGGEST month on-month decline belongs to category 'Fuel'
round(biggest_growth.min(),2)

-90.5

## ***TIME OF DAY PATTERNS***

In [ ]:
# Extracting hour from the 'Time' column and storing it as an integer
df['hour'] = df['Time'].str[:2].astype(int)

In [ ]:
hour_pivot = df.pivot_table(values='Amount', index='category', columns='hour', aggfunc='sum')

In [ ]:
hour_pivot

hour,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
category,,,,,,,,,,,,,,,,,,,,,
Cafe,499.0,549.0,NaN,316.0,NaN,NaN,179.0,480.0,2289.0,1387.0,...,1332.0,1676.0,2704.0,3110.0,2562.0,584.0,1491.0,NaN,NaN,764.0
Cash Withdrawal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4000.0,10500.0,...,1000.0,NaN,5000.0,NaN,5000.0,NaN,1000.0,1000.0,4000.0,NaN
E-commerce,18650.0,9801.0,10246.0,14865.0,12018.0,17258.0,9249.0,10916.0,6537.0,40724.0,...,72584.0,7700.0,52046.0,35378.0,35272.0,12668.0,51190.0,35095.0,16182.0,15403.0
Entertainment,562.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1881.0,NaN,NaN,NaN,1426.0,NaN,343.0,NaN
Food Delivery,832.0,3017.0,928.0,1702.0,2618.0,3488.0,238.0,1498.0,3737.0,5299.0,...,4236.0,7891.0,5008.0,3951.0,13587.0,17300.0,18372.0,12123.0,9283.0,4662.0
Fuel,2675.0,2048.0,NaN,676.0,2010.0,2105.0,NaN,NaN,1727.0,2283.0,...,7828.0,11937.0,9343.0,NaN,1950.0,8351.0,705.0,11845.0,NaN,1641.0
Groceries,3895.0,1536.0,1717.0,7080.0,1169.0,NaN,1620.0,NaN,2430.0,2704.0,...,NaN,NaN,NaN,NaN,NaN,1248.0,2566.0,1891.0,NaN,2536.0
Investments,4883.0,15000.0,NaN,NaN,18834.0,4496.0,37717.0,NaN,NaN,4737.0,...,NaN,NaN,NaN,NaN,15000.0,4476.0,15000.0,NaN,15000.0,18628.0
Personal Transfer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2425.0,...,1828.0,NaN,2361.0,2487.0,864.0,1295.0,2548.0,1532.0,325.0,NaN
Quick Commerce,1542.0,1402.0,1778.0,4149.0,768.0,1448.0,4432.0,252.0,1835.0,9548.0,...,5975.0,3438.0,6154.0,948.0,6134.0,6992.0,7319.0,8498.0,3405.0,1669.0
Restaurants,NaN,NaN,1336.0,NaN,NaN,2126.0,859.0,NaN,8037.0,702.0,...,385.0,769.0,2896.0,1346.0,9673.0,6231.0,25171.0,6348.0,1145.0,NaN
Subscription,NaN,1038.0,1295.0,3479.0,2806.0,119.0,238.0,885.0,NaN,NaN,...,1473.0,NaN,NaN,NaN,NaN,1435.0,NaN,119.0,NaN,NaN
Subscriptions,NaN,NaN,NaN,550.0,1879.0,626.0,419.0,272.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Transport,706.0,260.0,358.0,337.0,577.0,2005.0,555.0,3924.0,4311.0,2789.0,...,2096.0,3767.0,3325.0,3751.0,3448.0,3759.0,4647.0,1622.0,1852.0,1458.0
Utilities,1941.0,3271.0,2625.0,NaN,1222.0,NaN,NaN,1711.0,6117.0,3004.0,...,4273.0,2060.0,602.0,2443.0,6738.0,1125.0,4162.0,1472.0,2695.0,386.0

In [ ]:
# Expenditure on food
food_expense = df[df['Type'] == 'debit'][df['category'] == 'Food Delivery']
night_food_order = food_expense[(food_expense['hour'] >= 21) | (food_expense['hour'] <= 1)] # 21 is for 9PM and 1 is for 1 AM

/tmp/ipykernel_2107/2756343967.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  food_expense = df[df['Type'] == 'debit'][df['category'] == 'Food Delivery']

In [ ]:
night_food_order

,Date,Time,Description,Type,Amount,Balance,Mode,Ref,date,hour,month,day_of_week,week_number,vendor_clean,category
23,2024-01-03,23:58,POS SWIGGY-RESTAURANT,debit,238.0,666548.0,UPI,TXN975271,2024-01-03,23,1,Wednesday,1,Swiggy,Food Delivery
31,05-Jan-24,00:51,POS ZOMATO,debit,438.0,658408.0,UPI,TXN362246,2024-01-05,0,1,Friday,1,Zomato,Food Delivery
39,05-Jan-24,21:30,POS ZOMATO,debit,695.0,652234.0,UPI,TXN809176,2024-01-05,21,1,Friday,1,Zomato,Food Delivery
64,08-Jan-24,21:23,BUNDL Tech P L,debit,238.0,644405.0,UPI,TXN827157,2024-01-08,21,1,Monday,2,Swiggy,Food Delivery
141,20 Jan 2024,23:53,UPI-SWIGGY-9474@HDFCBANK,debit,181.0,561646.0,UPI,TXN462974,2024-01-20,23,1,Saturday,3,Swiggy,Food Delivery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1198,12 Jun 2024,23:36,UPI-SWIGGY-INSTAMART@OKAXIS,debit,225.0,-230142.0,UPI,TXN385173,2024-06-12,23,6,Wednesday,24,Swiggy,Food Delivery
1211,14/06/24,21:37,ZOMATO-DINING,debit,632.0,-242175.0,UPI,TXN734604,2024-06-14,21,6,Friday,24,Zomato,Food Delivery
1219,15-Jun-24,22:55,Swiggy*Order,debit,425.0,-246766.0,UPI,TXN942918,2024-06-15,22,6,Saturday,24,Swiggy,Food Delivery
1250,19/06/24,21:57,BUNDL Tech P L,debit,404.0,-266852.0,UPI,TXN357284,2024-06-19,21,6,Wednesday,25,Swiggy,Food Delivery
1313,28 Jun 2024,21:33,BUNDL Tech P L,debit,589.0,-307229.0,UPI,TXN356161,2024-06-28,21,6,Friday,26,Swiggy,Food Delivery

In [ ]:
# Percentage of expenditure on Food Delivery from 9 PM to 11 PM
late_night_food = (len(night_food_order) / len(food_expense) * 100) if len(food_expense) > 0 else 0

In [ ]:
round(late_night_food,2)

20.64

In [ ]:
# Expenditure on Cafes
cafe_expense = df[df['Type'] == 'debit'][df['category'] == 'Cafe']

/tmp/ipykernel_2107/3363952741.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  cafe_expense = df[df['Type'] == 'debit'][df['category'] == 'Cafe']

In [ ]:
# Recording cafe expenditure between 8-11 AM
morn_cafe = cafe_expense[(cafe_expense['hour'] >= 8) | (cafe_expense['hour'] <= 11)]

In [ ]:
# Percentage of expenditure on cafe while visiting between 8 AM and 11 AM
morning_cafe = (len(morn_cafe) / len(cafe_expense) * 100) if len(cafe_expense) > 0 else 0

In [ ]:
morning_cafe

100.0

## ***ANOMALY DETECTION***

In [ ]:
category_mean = df.groupby('category')['Amount'].transform('mean')
category_std = df.groupby('category')['Amount'].transform('std')
df['z_score'] = (df['Amount'] - category_mean) / category_std
anomalies = df[df['z_score'] > 2] # transactions 2+ stddev above category mean

In [ ]:
anomalies

,Date,Time,Description,Type,Amount,Balance,Mode,Ref,date,hour,month,day_of_week,week_number,vendor_clean,category,z_score
49,07/01/24,08:38,POS BANGALORE RESTAURANT,debit,7314.0,-411932.0,UPI,TXN388441,2024-01-07,8,1,Sunday,1,RESTAURANT,Restaurants,3.588612
85,2024-01-12,18:16,BANGALORE ELEC SUPPLY,debit,2329.0,445521.0,UPI,TXN149405,2024-01-12,18,1,Friday,2,BESCOM,Utilities,2.037334
160,23-Jan-24,21:36,UPI-BIGBASKET@HDFCBANK,debit,1797.0,546871.0,UPI,TXN517643,2024-01-23,21,1,Tuesday,4,BigBasket,Quick Commerce,3.746245
169,24 Jan 2024,18:43,FLIPKART INDIA,debit,16260.0,-583293.0,UPI,TXN858498,2024-01-24,18,1,Wednesday,4,Flipkart,E-commerce,2.819266
171,24-Jan-24,21:37,POS INDIAN OIL BANGALORE,debit,10408.0,-323092.0,UPI,TXN781212,2024-01-24,21,1,Wednesday,4,IOCL,Fuel,2.246441
218,31/01/24,10:46,BIGBASKET BANGALORE,debit,1258.0,499047.0,UPI,TXN255851,2024-01-31,10,1,Wednesday,5,BigBasket,Quick Commerce,2.086020
269,07/02/24,17:28,UPI-AMAZONPAY@HDFCBANK,debit,21986.0,-360151.0,UPI,TXN988380,2024-02-07,17,2,Wednesday,6,Amazon,E-commerce,4.085484
335,2024-02-17,09:41,BIGBASKET BANGALORE,debit,1517.0,422809.0,UPI,TXN788793,2024-02-17,9,2,Saturday,7,BigBasket,Quick Commerce,2.883790
336,2024-02-17,11:52,UPI-AMAZONPAY@HDFCBANK,debit,13674.0,-611841.0,UPI,TXN649317,2024-02-17,11,2,Saturday,7,Amazon,E-commerce,2.247412
350,19 Feb 2024,06:01,UPI-BIGBASKET@HDFCBANK,debit,1293.0,411597.0,UPI,TXN440881,2024-02-19,6,2,Monday,8,BigBasket,Quick Commerce,2.193827
414,2024-02-26,20:09,POS BANGALORE RESTAURANT,debit,8383.0,-567033.0,UPI,TXN308266,2024-02-26,20,2,Monday,9,RESTAURANT,Restaurants,4.248941
450,02-Mar-24,11:58,AMAZON IN,debit,18273.0,-558650.0,UPI,TXN228115,2024-03-02,11,3,Saturday,9,Amazon,E-commerce,3.264410
475,05 Mar 2024,21:33,UPI-AMAZONPAY@HDFCBANK,debit,19917.0,-465439.0,UPI,TXN674071,2024-03-05,21,3,Tuesday,10,Amazon,E-commerce,3.627956
522,12/03/24,11:19,BIGBASKET BANGALORE,debit,1865.0,291976.0,UPI,TXN880623,2024-03-12,11,3,Tuesday,11,BigBasket,Quick Commerce,3.955698
541,2024-03-14,15:33,POS INDIAN OIL BANGALORE,debit,10505.0,-404618.0,UPI,TXN631778,2024-03-14,15,3,Thursday,11,IOCL,Fuel,2.276628
589,21/03/24,12:06,BUNDL TECH-INSTAMART,debit,825.0,227008.0,UPI,TXN638292,2024-03-21,12,3,Thursday,12,Swiggy,Food Delivery,2.514304
651,31/03/24,13:24,AMAZONIN MARKETPLACE,debit,15953.0,-394113.0,UPI,TXN255130,2024-03-31,13,3,Sunday,13,Amazon,E-commerce,2.751378
653,31/03/24,20:01,POS MEGHANA FOODS,debit,7931.0,-445522.0,UPI,TXN149269,2024-03-31,20,3,Sunday,13,MEGHANA FOODS,Restaurants,3.969737
696,05/04/24,14:09,INNOVATIVE RETAIL,debit,1582.0,138165.0,UPI,TXN592053,2024-04-05,14,4,Friday,14,BigBasket,Quick Commerce,3.084003
699,05/04/24,20:18,UPI-FLIPKART@HDFCBANK,debit,14305.0,-509536.0,UPI,TXN864670,2024-04-05,20,4,Friday,14,Flipkart,E-commerce,2.386948
712,08 Apr 2024,03:42,INNOVATIVE RETAIL,debit,1682.0,128215.0,UPI,TXN329537,2024-04-08,3,4,Monday,15,BigBasket,Quick Commerce,3.392023
744,12-Apr-24,12:05,UPI-SWIGGY-INSTAMART@OKAXIS,debit,829.0,112167.0,UPI,TXN616791,2024-04-12,12,4,Friday,15,Swiggy,Food Delivery,2.540325
761,14-Apr-24,21:08,UPI-SWIGGY-INSTAMART@OKAXIS,debit,824.0,87647.0,UPI,TXN178516,2024-04-14,21,4,Sunday,15,Swiggy,Food Delivery,2.507799
785,17/04/24,08:54,UPI-BESCOM-BILL@HDFCBANK,debit,2394.0,54804.0,UPI,TXN158579,2024-04-17,8,4,Wednesday,16,BESCOM,Utilities,2.132667
792,2024-04-18,06:05,BIGBASKET BANGALORE,debit,1518.0,52101.0,UPI,TXN686462,2024-04-18,6,4,Thursday,16,BigBasket,Quick Commerce,2.886871
822,23-Apr-24,10:40,INNOVATIVE RETAIL,debit,1249.0,36890.0,UPI,TXN224122,2024-04-23,10,4,Tuesday,17,BigBasket,Quick Commerce,2.058298
875,30-Apr-24,14:19,Amazon Pay India,debit,14886.0,-524422.0,UPI,TXN486265,2024-04-30,14,4,Tuesday,18,Amazon,E-commerce,2.515427
984,15/05/24,14:13,UPI-FLIPKART@HDFCBANK,debit,14416.0,-495231.0,UPI,TXN508819,2024-05-15,14,5,Wednesday,20,Flipkart,E-commerce,2.411494
1024,2024-05-20,10:40,INNOVATIVE RETAIL,debit,1856.0,-103708.0,UPI,TXN656164,2024-05-20,10,5,Monday,21,BigBasket,Quick Commerce,3.927976
1076,26-May-24,21:07,BUNDL TECH-INSTAMART,debit,821.0,-142525.0,UPI,TXN208055,2024-05-26,21,5,Sunday,21,Swiggy,Food Delivery,2.488284
1079,2024-05-27,14:46,UPI-FLIPKART@HDFCBANK,debit,17831.0,-437591.0,UPI,TXN685380,2024-05-27,14,5,Monday,22,Flipkart,E-commerce,3.166669
1130,03 Jun 2024,16:09,UPI-FLIPKART@HDFCBANK,debit,16369.0,-665455.0,UPI,TXN998920,2024-06-03,16,6,Monday,23,Flipkart,E-commerce,2.843370
1144,05-Jun-24,20:32,Amazon Pay India,debit,14874.0,-598167.0,UPI,TXN649950,2024-06-05,20,6,Wednesday,23,Amazon,E-commerce,2.512773
1174,09 Jun 2024,18:38,BANGALORE ELEC SUPPLY,debit,2331.0,681057.0,UPI,TXN493537,2024-06-09,18,6,Sunday,23,BESCOM,Utilities,2.040268
1187,11/06/24,02:40,BANGALORE ELEC SUPPLY,debit,2324.0,-229276.0,UPI,TXN707940,2024-06-11,2,6,Tuesday,24,BESCOM,Utilities,2.030001
1207,13/06/24,20:34,UPI-SWIGGY-INSTAMART@OKAXIS,debit,833.0,-239057.0,UPI,TXN174801,2024-06-13,20,6,Thursday,24,Swiggy,Food Delivery,2.566345
1291,25 Jun 2024,14:21,Amazon Pay India,debit,17504.0,-629345.0,UPI,TXN103223,2024-06-25,14,6,Tuesday,26,Amazon,E-commerce,3.094358
1298,26 Jun 2024,09:07,AMAZONIN MARKETPLACE,debit,22008.0,-699028.0,UPI,TXN313051,2024-06-26,9,6,Wednesday,26,Amazon,E-commerce,4.090349
1308,27-Jun-24,16:33,FLIPKART INDIA,debit,15955.0,-540377.0,UPI,TXN403768,2024-06-27,16,6,Thursday,26,Flipkart,E-commerce,2.751820

In [ ]:
# Number of Anomalies
len(anomalies)

39

In [ ]:
top_2_anomalies = anomalies.sort_values(by='z_score', ascending=False).head(2)
display(top_2_anomalies[['date', 'vendor_clean', 'Amount', 'z_score']])

            date vendor_clean   Amount   z_score
414   2024-02-26   RESTAURANT   8383.0  4.248941
1298  2024-06-26       Amazon  22008.0  4.090349

## *SPENDING ARCHETYPE SYSTEM*

In [ ]:
# Total of debit transactions for each category measured by amount debited from the account
category_totals = df[df['Type'] == 'debit'].groupby('category')['Amount'].sum()

In [ ]:
# Calculating total amount debited for each category based on archetype guidelines
food_debits = category_totals['Food Delivery'] + category_totals['Restaurants'] + category_totals['Cafe']
qcom_debits = category_totals['Quick Commerce']
ecom_debits = category_totals['E-commerce']
inv_debits = category_totals['Investments']
trans_debits = category_totals['Transport']

In [ ]:
# Calculating amount spent on each category as a percentage of total debit transactions based on archetype guidelines
food_pct = (food_debits / total_debits) * 100
qcom_pct = (qcom_debits / total_debits) * 100
ecom_pct = (ecom_debits / total_debits) * 100
inv_pct = (inv_debits / total_debits) * 100
trans_pct = (trans_debits / total_debits) * 100

In [ ]:
# Computing number of active subscriptions
active_sub_suppliers = df[df['category'] == 'Subscriptions']['vendor_clean'].nunique()

In [ ]:
# Categorising Rahul based on the following archetypes

archetypes = []
if food_pct > 25:
 archetypes.append(f"THE FOODIE ({food_pct:.1f}% on food)")
if qcom_pct > 15:
 archetypes.append(f"THE QUICK COMMERCE JUNKIE ({qcom_pct:.1f}% on Q-com)")
if ecom_pct > 15:
 archetypes.append(f"THE SHOPAHOLIC ({ecom_pct:.1f}% on e-commerce)")
if inv_pct > 15:
  archetypes.append(f"THE INVESTOR ({inv_pct:.1f}% on SIPs)")
if late_night_food > 50:
 archetypes.append(f"THE LATE-NIGHT SNACKER ({late_night_food:.0f}% food after 9 PM)")
if trans_pct > 10:
 archetypes.append(f"THE CAB COMMUTER ({trans_pct:.1f}% on cab rides)")
if active_sub_suppliers >= 5:
 archetypes.append(f"THE SUBSCRIPTION LOVER ({active_sub_suppliers} active subs)")
if savings_rate < 10:
 archetypes.append(f"THE YOLO SPENDER (savings rate {savings_rate:.1f}%)")
if savings_rate > 40:
 archetypes.append(f"THE DISCIPLINED SAVER (savings rate {savings_rate:.1f}%)")

In [ ]:
# Bonus Archetype:
if (inv_pct > 15) and (food_pct > 25):
        archetypes.append("Indians are savers and hence are investors. But most importantly, we love food!")

In [ ]:
# Extension of Feature 6 to also analyse spending by day-of-week
day_pivot = df.pivot_table(values='Amount', index='category', columns='day_of_week', aggfunc='sum')

In [ ]:
day_pivot

day_of_week,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
category,,,,,,,
Cafe,4730.0,4364.0,2479.0,4062.0,4750.0,5566.0,2204.0
Cash Withdrawal,2000.0,7000.0,11000.0,NaN,2000.0,16000.0,7500.0
E-commerce,61947.0,85145.0,77440.0,55359.0,54122.0,121414.0,148450.0
Entertainment,NaN,NaN,NaN,952.0,1379.0,NaN,1881.0
Food Delivery,18993.0,20953.0,25213.0,22818.0,20158.0,18476.0,24228.0
Fuel,5122.0,10045.0,11319.0,14263.0,20687.0,2884.0,24983.0
Groceries,5145.0,4791.0,3222.0,6249.0,502.0,5223.0,12331.0
Investments,15000.0,19389.0,72861.0,15000.0,39359.0,52717.0,33834.0
Personal Transfer,3381.0,3977.0,NaN,1541.0,2314.0,3062.0,5564.0
Quick Commerce,13720.0,19318.0,14470.0,11510.0,12875.0,9503.0,14430.0
Restaurants,4004.0,15344.0,8830.0,20318.0,9603.0,11115.0,12025.0
Subscription,1495.0,631.0,3753.0,1520.0,2768.0,1272.0,2480.0
Subscriptions,753.0,526.0,210.0,969.0,NaN,600.0,1494.0
Transport,8927.0,11044.0,6505.0,7733.0,8487.0,8340.0,6438.0
Utilities,5132.0,7494.0,6758.0,11879.0,4901.0,6480.0,8111.0

In [ ]:
day_pivot[['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']].sum()

day_of_week
Monday       210021.0
Tuesday      262652.0
Wednesday    305953.0
Thursday     183905.0
Friday       150349.0
Saturday     244060.0
Sunday       174173.0
dtype: float64

In [ ]:
# AI - Assisted
# Sums down each column to get total spending per day

total_daily_spends = day_pivot.sum() # Sums down each column to get total spending per day

total_weekend_spends = total_daily_spends[['Saturday', 'Sunday']].sum()
total_weekday_spends = total_daily_spends[['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']].sum()

is_50_percent_more_expensive = total_weekend_spends > (total_weekday_spends * 0.5)

print(f"Total weekend spending: {total_weekend_spends:.2f}")
print(f"Total weekday spending: {total_weekday_spends:.2f}")
print(f"Are weekends 50% more expensive than weekdays? {is_50_percent_more_expensive}")

Total weekend spending: 418233.00
Total weekday spending: 1112880.00
Are weekends 50% more expensive than weekdays? False

In [ ]:
# Transaction Uncategorised
df[df['vendor_clean']=='Uncategorised']['Description'].unique()

array(['IMPS-RENT-LANDLORD-75500265', 'IMPS-RENT-LANDLORD-39598076',
       'IMPS-RENT-LANDLORD-51148088', 'IMPS-RENT-LANDLORD-36852906',
       'IMPS-RENT-LANDLORD-49966195', 'IMPS-RENT-LANDLORD-35126704'],
      dtype=object)

In [ ]:
# SPEND FORECASTING
forecast={}
for category in month_pivot.index:
    forecast[category]=np.mean(month_pivot.loc[category,["Apr","May","Jun"]].values)

In [ ]:
forecast

{'Cafe': np.float64(5405.666666666667),
 'Cash Withdrawal': np.float64(10166.666666666666),
 'E-commerce': np.float64(101009.33333333333),
 'Entertainment': np.float64(nan),
 'Food Delivery': np.float64(26554.333333333332),
 'Fuel': np.float64(10246.0),
 'Groceries': np.float64(5112.666666666667),
 'Investments': np.float64(42028.0),
 'Personal Transfer': np.float64(1872.0),
 'Quick Commerce': np.float64(15061.666666666666),
 'Restaurants': np.float64(12199.0),
 'Subscription': np.float64(1835.6666666666667),
 'Subscriptions': np.float64(686.6666666666666),
 'Transport': np.float64(9807.0),
 'Utilities': np.float64(8291.666666666666)}

# ***FINAL REPORT***

In [ ]:
print("="*70)
print("== SpendDNA REPORT - RAHUL SHARMA")
print(f"6 months - {len(df)} transactions - Jan to Jun 2024")
print("="*70)
print("")
print("EXECUTIVE SUMMARY")
print(f"Total credits: Rs.{total_credits:.2f}")
print(f"Total debits: Rs.{total_debits:.2f}")
print(f"Net change: Rs.{total_savings:.2f} (overspending)")
print(f"Savings rate: {savings_rate:.2f}% (BURNING SAVINGS)")
print(f"Transactions: {len(df)}")
print(f"Unique vendors: {df['vendor_clean'].nunique()}")
print("")
print("TOP CATEGORIES (% of debit total)")
print(f"Food Delivery ################## {round(food_percent_deb,2)}% Rs. {category_spends['Food Delivery']} ")
print(f"E-commerce ################## {round(ecom_percent_deb,2)}% Rs. {category_spends['E-commerce']}")
print(f"Quick Commerce ################## {round(qcom_percent_deb,2)}% Rs. {category_spends['Quick Commerce']}")
print(f"Investments ################## {round(inv_percent_deb,2)}%  Rs. {category_spends['Investments']}")
print(f"Restaurants ################## {round(rest_percent_deb,2)}% Rs. {category_spends['Restaurants']}")
print("")
print("TOP VENDORS (% of total debits)")
print(f"Amazon Rs. {vendor_spends['Amazon']} ({len(df[df['vendor_clean'] == 'Amazon'])} orders) ")
print(f"Zerodha Rs. {vendor_spends['Zerodha']} ({len(df[df['vendor_clean'] == 'Zerodha'])} SIPs) ")
print(f"Flipkart Rs. {vendor_spends['Flipkart']} ({len(df[df['vendor_clean'] == 'Flipkart'])} orders) ")
print(f"Swiggy Rs. {vendor_spends['Swiggy']} ({len(df[df['vendor_clean'] == 'Swiggy'])} orders) ")
print(f"Myntra Rs. {vendor_spends['Myntra']} ({len(df[df['vendor_clean'] == 'Myntra'])} orders) ")
print("")
print("TIME-OF-DAY PATTERNS")
print(f"Food Delivery peaks: 21:00 - 01:00 ({late_night_food:.0f}% of orders)")
print("Cafe peaks: 09:00 - 11:00 (morning runs)")
print("Quick Commerce: evenly distributed")
print("")
print("MONTHLY TREND (Food Delivery)")
print(f"{month_pivot.loc[['Food Delivery']]}")
print("")
print("TOP ANOMALIES (3+ stddev from category mean)")
print("")
print(f"{top_2_anomalies[['date', 'vendor_clean', 'Amount', 'z_score']]}")

======================================================================
== SpendDNA REPORT - RAHUL SHARMA
6 months - 1310 transactions - Jan to Jun 2024
======================================================================

EXECUTIVE SUMMARY
Total credits: Rs.509774.00
Total debits: Rs.1678901.00
Net change: Rs.-1169127.00 (overspending)
Savings rate: -229.34% (BURNING SAVINGS)
Transactions: 1310
Unique vendors: 42

TOP CATEGORIES (% of debit total)
Food Delivery ################## 8.98% Rs. 150839.0
E-commerce ################## 35.97% Rs. 603877.0
Quick Commerce ################## 5.71% Rs. 95826.0
Investments ################## 14.78%  Rs. 248160.0
Restaurants ################## 4.84% Rs. 81239.0

TOP VENDORS (% of total debits)
Amazon Rs. 328530.0 (86 orders)
Zerodha Rs. 210000.0 (14 SIPs)
Flipkart Rs. 177510.0 (47 orders)
Swiggy Rs. 95523.0 (223 orders)
Myntra Rs. 69529.0 (20 orders)

TIME-OF-DAY PATTERNS
Food Delivery peaks: 21:00 - 01:00 (21% of orders)
Cafe peaks: 09:00 - 11:00 (morning runs)
Quick Commerce: evenly distributed

MONTHLY TREND (Food Delivery)
month              Jan      Feb      Mar      Apr      May      Jun
category
Food Delivery  22633.0  23740.0  24803.0  27756.0  25408.0  26499.0

TOP ANOMALIES (3+ stddev from category mean)

            date vendor_clean   Amount   z_score
414   2024-02-26   RESTAURANT   8383.0  4.248941
1298  2024-06-26       Amazon  22008.0  4.090349

## **REFLECTION CELL**

This project was an extremely useful practice for students who aspire to become Data Analysts in Banks. The three most insightful aspects about this project for me were:

a) Categorisation of vendors
b) Calculation of Z_Score which could be used to check financial stability and proper use of savings by an individual

c) Monthly Trend Analysis which shows the increase in Rahul's expenditure towards vendors favourable to him

This project was fun but a tedious task. I have taken the help of AI in certain calculations and have declared the same in specific cells